#!/bin/bash

source nb-slurm/yaml_parser

eval $(parse_yaml nb-slurm/default.yaml "OPT_")
eval $(parse_yaml nb-slurm/config.yaml "OPT_")

# Declare variables
memory=$OPT_memory
cores=$OPT_cores
time=$OPT_time
debug=""

# Print a user-friendly usage guide
print_usage(){
        printf "Usage: launch_rstudio [OPTION]

  -m [memory]   request memory (default: $memory)
  -c [cores]    request number of cores (default: $cores)
  -t [time]     request time (default: $time)
  -d            run in debug mode (1GB memory, 1 core, 1h)
  -h            display this message

NOTE: long-form options (e.g., --memory 10G) are not supported
"
}

while getopts 'm:c:t:dh' flag; do
  case "${flag}" in
    m) memory="${OPTARG}" ;;
    c) cores="${OPTARG}" ;;
    t) time="${OPTARG}" ;;
    d) debug='true' ;;
    h) print_usage
       exit 1 ;;
    *) error "Unexpected option ${flag}"
       exit 1 ;;
  esac
done

if [ "${debug}" == 'true' ]; then
        partition="debug"
        memory="1G"
        cores="1"
        time="01:00:00"
fi

echo "Requesting node with ${memory} of memory and ${cores} cores, walltime ${time}..."

salloc \
        --nodes=1 \
        --ntasks-per-node=1 \
        --cpus-per-task="${cores}" \
        --mem="${memory}" \
        --job-name="jupyter_notebook" \
        --time="${time}" \
        --partition="${OPT_partition}" \
        --account="${OPT_account}" \
        srun nb-slurm/rstudio
